services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./broker/config:/mosquitto/config
      - ./broker/log:/mosquitto/log
    user: 1000:1000
  mqtt-client:
    build: ./client
